### ISSUE TITLE
i find a bug ..

### ISSUE THREAD

**Issue by minqi-source** [gisbi-kim/mulran-evaluation#1]
First of all, thank you for open source.
When I run, I have the following problem

(matlab R2019a) the example **global_pose_dcc01.csv** to **lidarcoord_pose_dcc01.csv** is ok,and to **lidarcoord_pose_dcc01_tum_format.csv** is ok

but **lidarcoord_pose_dcc02.csv** to **lidarcoord_pose_dcc02_tum_format.csv** :
 Quaternion/set.s (line 139)
s must be real scalar

 UnitQuaternion (line 198)
                uq.s = s/n;

 UnitQuaternion (line 190)
                    uq(i) = UnitQuaternion(qs,qv);

reformatKITTI2TUM (line 15)
    rotquat = UnitQuaternion(rotso3);

**Comment by gisbi-kim** [comment]
Thank you for the error report. 

I just added try-catch block to handle (i.e., skip the error) 
I saw a few tens of lines would be removed via skipping 
However, there is no problem in doing the evaluation because we have corresponding timestamps for the remaining poses lines.
